# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Fastline 自动化升级维护私有库"
  lane :update_spec do |options|
    target_version = options[:version]
    project        = 'XBCategoryKit'
#options[:project]
    path           = "#{project}.podspec"

    # 1、修改spec文件（修改s.version，s.description等）
    # 2、pod install （使Example与pod下来的库产生关联）
    cocoapods(
      clean: true,
      podfile: "./Example/Podfile"
    )

  

    # 3、提交本地仓库代码至远程仓库
    git_add(path: ".")
    git_commit(path: ".", message: "upgrade repo")
    push_to_git_remote

    # 4、打标签，并提交至远程
    add_git_tag(
      tag: target_version
    )
    push_git_tags

    # 5、验证spec，并提至私有索引库
    pod_lib_lint(allow_warnings: true)
    # 因为本地索引库repo的名字是基本上不会去改变的，所以这里直接写死 XBSpecs
    # podspec的名字需要由外界传入
    pod_push(path: "#{project}.podspec", repo: "XBSpecs", allow_warnings: true)


  end
end

